# Generated by Django 5.2.2 on 2025-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[("MONTH", "Monthly"), ("YEAR", "Yearly")],
                        default="MONTH",
                        max_length=10,
                    ),
                ),
                (
                    "paypal_plan_id",
                    models.CharField(
                        help_text="PayPal Plan ID from PayPal dashboard or SDK",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
