# Generated by Django 5.2.2 on 2025-07-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paypal_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
