# Generated by Django 4.2.23 on 2025-07-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_trial_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_pending",
            field=models.BooleanField(default=False),
        ),
    ]
