# Generated by Django 4.2.23 on 2025-07-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_subscription_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paypal_plan_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
