# Generated by Django 4.2.23 on 2025-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_paypal_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="paypal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
