# Generated by Django 4.2.23 on 2025-07-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_paypal_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="paypal_email",
        ),
    ]
