# Generated by Django 5.2.2 on 2025-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_remove_transaction_product_name_transaction_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
