# Generated by Django 4.2.23 on 2025-07-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
