# Generated by Django 4.2.23 on 2025-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0005_alter_transaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="capture_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
