# Generated by Django 4.2.23 on 2025-07-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_transaction_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                    ("denied", "Denied"),
                    ("disputed", "Disputed"),
                ],
                default="success",
                max_length=20,
            ),
        ),
    ]
